## makefile

all: compile execute

compile:
	g++-10 -Wall -o main.out $(wildcard *.cpp) -fopenmp -std=c++11 -Ofast

execute:
	./main.out

#cpp - python interface example
#plotmc:
#	python3 plotcycles.py
